# Form implementation generated from reading ui file 'src/ui/ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 449)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 811, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.messages_widget = QtWidgets.QListWidget(parent=self.tab)
        self.messages_widget.setGeometry(QtCore.QRect(10, 10, 791, 221))
        self.messages_widget.setObjectName("messages_widget")
        self.message_text = QtWidgets.QLineEdit(parent=self.tab)
        self.message_text.setGeometry(QtCore.QRect(10, 240, 791, 41))
        self.message_text.setObjectName("message_text")
        self.send_message = QtWidgets.QPushButton(parent=self.tab)
        self.send_message.setGeometry(QtCore.QRect(10, 290, 421, 81))
        self.send_message.setObjectName("send_message")
        self.quit_from_chat = QtWidgets.QPushButton(parent=self.tab)
        self.quit_from_chat.setGeometry(QtCore.QRect(440, 290, 361, 81))
        self.quit_from_chat.setObjectName("quit_from_chat")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.server_ip = QtWidgets.QLineEdit(parent=self.tab_2)
        self.server_ip.setGeometry(QtCore.QRect(0, 0, 791, 51))
        self.server_ip.setObjectName("server_ip")
        self.server_port = QtWidgets.QLineEdit(parent=self.tab_2)
        self.server_port.setGeometry(QtCore.QRect(0, 60, 791, 51))
        self.server_port.setObjectName("server_port")
        self.user_nikname = QtWidgets.QLineEdit(parent=self.tab_2)
        self.user_nikname.setGeometry(QtCore.QRect(0, 120, 791, 51))
        self.user_nikname.setObjectName("user_nikname")
        self.connect_to_server = QtWidgets.QPushButton(parent=self.tab_2)
        self.connect_to_server.setGeometry(QtCore.QRect(0, 310, 391, 71))
        self.connect_to_server.setObjectName("connect_to_server")
        self.save_settings = QtWidgets.QPushButton(parent=self.tab_2)
        self.save_settings.setGeometry(QtCore.QRect(400, 310, 391, 71))
        self.save_settings.setObjectName("save_settings")
        self.label = QtWidgets.QLabel(parent=self.tab_2)
        self.label.setGeometry(QtCore.QRect(150, 380, 521, 16))
        self.label.setObjectName("label")
        self.avatar = QtWidgets.QLabel(parent=self.tab_2)
        self.avatar.setGeometry(QtCore.QRect(0, 180, 131, 131))
        self.avatar.setText("")
        self.avatar.setPixmap(QtGui.QPixmap("src/ui/../../../../.achat/user.png"))
        self.avatar.setScaledContents(True)
        self.avatar.setObjectName("avatar")
        self.chose_avatar = QtWidgets.QPushButton(parent=self.tab_2)
        self.chose_avatar.setGeometry(QtCore.QRect(130, 190, 661, 61))
        self.chose_avatar.setObjectName("chose_avatar")
        self.set_default_avatar = QtWidgets.QPushButton(parent=self.tab_2)
        self.set_default_avatar.setGeometry(QtCore.QRect(130, 250, 661, 61))
        self.set_default_avatar.setObjectName("set_default_avatar")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_text.setPlaceholderText(_translate("MainWindow", "Введіть сюди ваше повідомлення"))
        self.send_message.setText(_translate("MainWindow", "Відправити"))
        self.quit_from_chat.setText(_translate("MainWindow", "Вийти з чату"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Чат"))
        self.server_ip.setPlaceholderText(_translate("MainWindow", "IP сервера"))
        self.server_port.setPlaceholderText(_translate("MainWindow", "Порт сервера"))
        self.user_nikname.setPlaceholderText(_translate("MainWindow", "Нікнейм"))
        self.connect_to_server.setText(_translate("MainWindow", "Підключитися"))
        self.save_settings.setText(_translate("MainWindow", "Зберегти налаштування"))
        self.label.setText(_translate("MainWindow", "Файл налаштуваннь зберігається у папці .achat у директорії вашого користувача"))
        self.chose_avatar.setText(_translate("MainWindow", "Вибрати..."))
        self.set_default_avatar.setText(_translate("MainWindow", "Встановити за замовчюванням"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Налаштування"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
